version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /about.html
    destination: /var/www/html/
  - source: /blog-single.html
    destination: /var/www/html/
  - source: /blog.html
    destination: /var/www/html/
  - source: /contact.html
    destination: /var/www/html/
  - source: /index-2.html
    destination: /var/www/html/
  - source: /portfolio-detais.html
    destination: /var/www/html/
  - source: /portfolio.html
    destination: /var/www/html/
  - source: /services.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

